feat: device interface enumeration completely rewritten feat: vm interface enumeration completely rewritten feat: remove Device Interface Type Detection feat: add feature that will not overrite device interface type if set in netbox (idempotency) fix: improve variable distribution (moved out of main)

diff --git a/roles/hostsync/tasks/device/interface_detect.yml b/roles/hostsync/tasks/device/interface_detect.yml
--- a/roles/hostsync/tasks/device/interface_detect.yml
+++ b/roles/hostsync/tasks/device/interface_detect.yml
@@ -71,40 +71,78 @@
   ansible.builtin.debug:
     var: _device_bridges
 
+- name: SFP detection skipped (non-root or disabled)
+  when:
+    - not hostsync_device_features['sfp'] | default(true) | bool
+  ansible.builtin.debug:
+    msg: "SFP detection disabled. Defaulting all interfaces to 'tp'."
+
+- name: Detect SFP capability (wired NICs only)
+  become: true
+  changed_when: false
+  failed_when: false
+  register: _sfp_mod
+  loop: "{{ _device_phys }}"
+  loop_control:
+    loop_var: diface_p
+    label: "{{ diface_p }}"
+  when:
+    - _device_phys | length > 0
+    - hostsync_sfp_check | default(true) | bool
+    - diface_p is match(hostsync_sfp_naming_regex)
+    - (diface_facts[diface_p].pciid is defined or diface_facts[diface_p].module is defined)
+  ansible.builtin.shell: |
+    out="$(ethtool -m {{ diface_p }} 2>&1)"; rc=$?
+    if [ $rc -eq 0 ] && ! echo "$out" | grep -qiE 'operation not supported|not supported|no eeprom|netlink error|no such device'; then
+      echo "sfp"
+    else
+      echo "tp"
+    fi
+
+
+- name: Ensure port-kind map exists if SFP check is disabled or no phys NICs
+  when:
+    - _device_phys | length == 0 or not hostsync_device_features['sfp'] | default(true) | bool
+  ansible.builtin.set_fact:
+    _hostsync_port_kind: {}
+
+# - name: Build iface -> port kind map from _sfp_mod
+#   delegate_to: localhost
+#   when:
+#     - _device_phys | length > 0
+#     - _sfp_mod is defined
+#     - _sfp_mod.results is defined
+#   ansible.builtin.set_fact:
+#     _hostsync_port_kind: "{{ dict(_sfp_mod.results | map(attribute='diface_p') | zip(_sfp_mod.results | map(attribute='stdout') | map('trim'))) }}"
+
+- name: Build iface -> port kind map from _sfp_mod
+  delegate_to: localhost
+  when:
+    - _device_phys | length > 0
+    - hostsync_device_features['sfp'] | default(true) | bool
+    - _sfp_mod is defined
+    - _sfp_mod.results is defined
+  ansible.builtin.set_fact:
+    _hostsync_port_kind: >-
+      {{
+        dict(
+          _sfp_mod.results | map(attribute='diface_p')
+          | zip(_sfp_mod.results | map(attribute='stdout') | map('trim'))
+        )
+      }}
+
 - name: Ensure port-kind map exists (no phys NICs)
   when:
     - _device_phys | length == 0
   ansible.builtin.set_fact:
     _hostsync_port_kind: {}
 
-# - - - - - -
-
-- name: Get existing interfaces for device (NetBox)
+- name: Debug _sfp_mod
   delegate_to: localhost
-  vars:
-    _q: ('device=' ~ hostsync_hostname)
-  ansible.builtin.set_fact:
-    _nb_existing_ifaces: >-
-      {{
-        query('netbox.netbox.nb_lookup', 'interfaces',
-               api_endpoint=hostsync_netbox_api,
-               token=hostsync_netbox_api_key,
-               validate_certs=hostsync_netbox_validcert,
-               api_filter="device=" ~hostsync_hostname)
-      }}
-# {{
-#   lookup('netbox.netbox.nb_lookup',
-#          'interfaces',
-#          api_endpoint=hostsync_netbox_api,
-#          token=hostsync_netbox_api_key,s
-#          validate_certs=hostsync_netbox_validcert,
-#          query=_q)
-# }}
-
-- name: Build set of existing interface names
-  delegate_to: localhost
-  ansible.builtin.set_fact:
-    _nb_existing_iface_names: "{{ _nb_existing_ifaces | map(attribute='value.name') | list }}"
+  when:
+    - ansible_check_mode
+  ansible.builtin.debug:
+    var: _hostsync_port_kind
 
 # - - - - - -
 
@@ -151,13 +189,6 @@
             | default(diface_facts[diface_bond].macaddress)
             | default(omit)
         }}
-      primary_mac_address: >-
-        {{
-          omit if hostsync_netbox_version is version(4.2, '<') else
-          diface_facts[diface_bond].perm_macaddress
-            | default(diface_facts[diface_bond].macaddress)
-            | default(omit)
-        }}
       mtu: "{{ diface_facts[diface_bond].mtu | default(omit) }}"
       tags: "{{ hostsync_add_tags }}"
     state: present
@@ -193,6 +224,7 @@
   vars:
     _port_kind: "{{ _hostsync_port_kind[diface_phys] | default('tp') }}"
     _speed_key: "{{ (diface_facts[diface_phys].speed | default(-1)) | int | string }}"
+    _slug: "{{ _hostsync_iftype_logic_slugs[_port_kind][_speed_key] | default('other') }}"
     _lag_master: >-
       {{
         (_device_bonds | select('in',
@@ -202,7 +234,7 @@
             | map(attribute='key') | list)
         ) | list | first) | default(omit)
       }}
-    _type_on_create: "{{ 'other' if (diface_phys not in _nb_existing_iface_names) else omit }}"
+    # _type_slug: "{{ _hostsync_iface_type_map[item] | default('other') }}"
   netbox.netbox.netbox_device_interface:
     netbox_url: "{{ hostsync_netbox_api }}"
     netbox_token: "{{ hostsync_netbox_api_key }}"
@@ -210,17 +242,10 @@
     data:
       device: "{{ hostsync_hostname }}"
       name: "{{ diface_phys }}"
-      type: "{{ _type_on_create }}"
+      type: "{{ _slug | default('other') }}"
       enabled: "{{ diface_facts[diface_phys].active | default(true) }}"
       mac_address: >-
         {{
-          diface_facts[diface_phys].perm_macaddress
-            | default(diface_facts[diface_phys].macaddress)
-            | default(omit)
-        }}
-      primary_mac_address: >-
-        {{
-          omit if hostsync_netbox_version is version(4.2, '<') else
           diface_facts[diface_phys].perm_macaddress
             | default(diface_facts[diface_phys].macaddress)
             | default(omit)
